### ISSUE TITLE
Does not compile with go 1.3 (so you said)

### ISSUE THREAD

**Issue by arnonym** [clausecker/nfc#3]
# go get github.com/fuzxxl/nfc/1.0/nfc
src/github.com/fuzxxl/nfc/1.0/nfc/nfc.go:205: undefined: context
